version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
      nodejs: 18
    commands:
      - npm install -g aws-cdk
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Deploying CdkPipelineLabStack..."
      - cdk deploy CdkPipelineLabStack --require-approval never

artifacts:
  base-directory: cdk.out
  files:
    - '**/*'