version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
      nodejs: 18
    commands:
      - npm install -g aws-cdk
      - pip install -r requirements.txt

  build:
    commands:
      - cdk synth CdkPipelineLabStack
      - echo "Publishing assets to S3..."
      - |
        for asset in $(find cdk.out -name "*.assets.json"); do
          echo "Publishing assets from $asset"
          npx cdk-assets publish -p $asset || true
        done

artifacts:
  base-directory: cdk.out
  files:
    - '**/*'